newline_style = "Unix"
tab_spaces = 2
#condense_wildcard_suffixes = true
#format_code_in_doc_comments = true
#group_imports = "StdExternalCrate"
#imports_granularity = "Crate"
#normalize_comments = true
#normalize_doc_attributes = true
#wrap_comments = true
